version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bulletquest
      - JWT_SECRET=seu_jwt_secret_aqui
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma generate && npx prisma migrate deploy && yarn dev"

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bulletquest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 